#!/usr/bin/env bash
# Summary: Show the current PHP version and its origin
#
# Shows the currently selected PHP version and how it was
# selected. To obtain only the version string, use `mammoth
# version-name'.

set -e
[ -n "$MAMMOTH_DEBUG" ] && set -x

echo "$(mammoth-version-name) (set by $(mammoth-version-origin))"
