#!/usr/bin/env bash
# Usage: mammoth completions <command> [arg1 arg2...]

set -e
[ -n "$MAMMOTH_DEBUG" ] && set -x

COMMAND="$1"
if [ -z "$COMMAND" ]; then
  mammoth-help --usage completions >&2
  exit 1
fi

COMMAND_PATH="$(command -v "mammoth-$COMMAND" || command -v "mammoth-sh-$COMMAND")"
if grep -i "^# provide mammoth completions" "$COMMAND_PATH" >/dev/null; then
  shift
  exec "$COMMAND_PATH" --complete "$@"
fi
