#!/usr/bin/env bash
# Summary: List all PHP versions available to mammoth
# Usage: mammoth versions [--bare]
#
# Lists all PHP versions found in `$MAMMOTH_ROOT/versions/*'.

set -e
[ -n "$MAMMOTH_DEBUG" ] && set -x

if [ "$1" = "--bare" ]; then
  hit_prefix=""
  miss_prefix=""
  current_version=""
  include_system=""
else
  hit_prefix="* "
  miss_prefix="  "
  current_version="$(mammoth-version-name || true)"
  include_system="1"
fi

print_version() {
  if [ "$1" == "$current_version" ]; then
    echo "${hit_prefix}$(mammoth-version 2>/dev/null)"
  else
    echo "${miss_prefix}$1"
  fi
}

# Include "system" in the non-bare output, if it exists
if [ -n "$include_system" ] && MAMMOTH_VERSION=system mammoth-which php >/dev/null 2>&1; then
  print_version system
fi

for path in "${MAMMOTH_ROOT}/versions/"*; do
  if [ -d "$path" ]; then
    print_version "${path##*/}"
  fi
done
