#!/usr/bin/env bash
set -e
export -n CDPATH

if [ "$1" = "--debug" ]; then
  export MAMMOTH_DEBUG=1
  shift
fi

if [ -n "$MAMMOTH_DEBUG" ]; then
  export PS4='+ [${BASH_SOURCE##*/}:${LINENO}] '
  set -x
fi

resolve_link() {
  $(type -p greadlink readlink | head -1) "$1"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

if [ -z "${MAMMOTH_ROOT}" ]; then
  MAMMOTH_ROOT="${HOME}/.mammoth"
else
  MAMMOTH_ROOT="${MAMMOTH_ROOT%/}"
fi
export MAMMOTH_ROOT

if [ -z "${MAMMOTH_DIR}" ]; then
  MAMMOTH_DIR="$(pwd)"
else
  cd "$MAMMOTH_DIR" 2>/dev/null || {
    echo "mammoth: cannot change working directory to \`$MAMMOTH_DIR'"
    exit 1
  } >&2
  MAMMOTH_DIR="$(pwd)"
  cd "$OLDPWD"
fi
export MAMMOTH_DIR


shopt -s nullglob

bin_path="$(abs_dirname "$0")"
for plugin_bin in "${MAMMOTH_ROOT}/plugins/"*/bin; do
  bin_path="${bin_path}:${plugin_bin}"
done
export PATH="${bin_path}:${PATH}"

hook_path="${MAMMOTH_HOOK_PATH}:${MAMMOTH_ROOT}/mammoth.d:/usr/local/etc/mammoth.d:/etc/mammoth.d:/usr/lib/mammoth/hooks"
for plugin_hook in "${MAMMOTH_ROOT}/plugins/"*/etc/mammoth.d; do
  hook_path="${hook_path}:${plugin_hook}"
done
export MAMMOTH_HOOK_PATH="$hook_path"

shopt -u nullglob

command="$1"
if [[ "$2" = "--help"  || "$2" = "-h"  ]]; then
  mammoth-help "$command" >&2
  exit 1
fi

case "$command" in
"" | "-h" | "--help" )
  echo -e "$(mammoth-help)" >&2
  ;;
"-v" )
  exec mammoth---version
  ;;
* )
  command_path="$(command -v "mammoth-$command" || true)"
  if [ -z "$command_path" ]; then
    echo "mammoth: no such command \`$command'" >&2
    exit 1
  fi

  shift 1
  exec "$command_path" "$@"
  ;;
esac
