#!/usr/bin/env bash
# Summary: Display the version of mammoth
#
# Displays the version number of this mammoth release, including the
# current revision from git, if available.
#
# The format of the git revision is:
#   <version>-<num_commits>-<git_sha>
# where `num_commits` is the number of commits since `version` was
# tagged.

set -e
[ -n "$MAMMOTH_DEBUG" ] && set -x

version="0.9.0-rc.1"
git_revision=""

cd "$MAMMOTH_ROOT"
git_revision="$(git describe --tags HEAD 2>/dev/null || true)"
git_revision="${git_revision#v}"

echo "mammoth v${git_revision:-$version}"
