#!/usr/bin/env bash
# Summary: List all PHP versions that contain the given executable
# Usage: mammoth whence [--path] <command>

set -e
[ -n "$MAMMOTH_DEBUG" ] && set -x

# Provide mammoth completions
if [ "$1" = "--complete" ]; then
  echo --path
  exec mammoth shims --short
fi

if [ "$1" = "--path" ]; then
  print_paths="1"
  shift
else
  print_paths=""
fi

whence() {
  local command="$1"
  mammoth-versions --bare | while read version; do
    path="$(mammoth-prefix "$version")/bin/${command}"
    if [ -x "$path" ]; then
      [ "$print_paths" ] && echo "$path" || echo "$version"
    fi
  done
}

MAMMOTH_COMMAND="$1"
if [ -z "$MAMMOTH_COMMAND" ]; then
  mammoth-help --usage whence >&2
  exit 1
fi

result="$(whence "$MAMMOTH_COMMAND")"
[ -n "$result" ] && echo "$result"
