#!/usr/bin/env bash
#
# Summary: Set or show the shell-specific PHP version
#
# Usage: mammoth shell <version>
#        mammoth shell --unset
#
# Sets a shell-specific PHP version by setting the `MAMMOTH_VERSION'
# environment variable in your shell. This version overrides local
# application-specific versions and the global version.
#
# <version> should be a string matching a PHP version known to mammoth.
# The special version string `system' will use your default system PHP.
# Run `mammoth versions' for a list of available PHP versions.

set -e
[ -n "$MAMMOTH_DEBUG" ] && set -x

# Provide mammoth completions
if [ "$1" = "--complete" ]; then
  echo --unset
  echo system
  exec mammoth-versions --bare
fi

version="$1"

if [ "$version" = "--unset" ]; then
  echo "unset MAMMOTH_VERSION" 2>/dev/null
  MAMMOTH_VERSION=""; version=""
fi


if [ -z "$version" ]; then
  if [ -z "$MAMMOTH_VERSION" ]; then
    echo "mammoth: no shell-specific version configured" >&2
    exit 1
  else
    echo "echo \"\$MAMMOTH_VERSION\""
    exit
  fi
fi

# Make sure the specified version is installed.
if mammoth-prefix "$version" >/dev/null; then
  echo "export MAMMOTH_VERSION=\"${version}\""
  echo "$version" >&2
else
  echo "return 1"
  exit 1
fi
