#!/usr/bin/env bash
# Summary: Detect the file that sets the current mammoth version
set -e
[ -n "$MAMMOTH_DEBUG" ] && set -x

find_local_version_file() {
  local root="$1"
  while [ -n "$root" ]; do
    if [ -e "${root}/.php-version" ]; then
      echo "${root}/.php-version"
      exit
    elif [ -e "${root}/.mammoth-version" ]; then
      echo "${root}/.mammoth-version"
      exit
    fi
    root="${root%/*}"
  done
}

find_local_version_file "$MAMMOTH_DIR"
[ "$MAMMOTH_DIR" = "$PWD" ] || find_local_version_file "$PWD"

global_version_file="${MAMMOTH_ROOT}/version"

if [ -e "$global_version_file" ]; then
  echo "$global_version_file"
elif [ -e "${MAMMOTH_ROOT}/global" ]; then
  echo "${MAMMOTH_ROOT}/global"
elif [ -e "${MAMMOTH_ROOT}/default" ]; then
  echo "${MAMMOTH_ROOT}/default"
else
  echo "$global_version_file"
fi
