#!/usr/bin/env bash
#
# Summary: Set or show the global PHP version and update the Apache apxs
# library link
#
# Usage: mammoth global <version>
#        mammoth global --unset
#
# Sets the global PHP version. You can override the global version at
# any time by setting a directory-specific version with `mammoth local'
# or by setting the `MAMMOTH_VERSION' environment variable.
#
# <version> should be a string matching a PHP version known to mammoth.
# The special version string `system' will use your default system PHP.
# Run `mammoth versions' for a list of available PHP versions.

set -e
[ -n "$MAMMOTH_DEBUG" ] && set -x

# Provide mammoth completions
if [ "$1" = "--complete" ]; then
  echo system --unset
  exec mammoth-versions --bare
fi

MAMMOTH_VERSION="$1"
MAMMOTH_VERSION_FILE="${MAMMOTH_ROOT}/version"

if [ "$1" == "--unset" ]; then
  rm -f "$MAMMOTH_VERSION_FILE"
  MAMMOTH_VERSION=""
fi

if [ -n "$MAMMOTH_VERSION" ]; then
  mammoth-version-file-write "$MAMMOTH_VERSION_FILE" "$MAMMOTH_VERSION"
else
  MAMMOTH_VERSION=$(mammoth-version-file-read "$MAMMOTH_VERSION_FILE") ||
  MAMMOTH_VERSION=$(mammoth-version-file-read "${MAMMOTH_ROOT}/global") ||
  MAMMOTH_VERSION=$(mammoth-version-file-read "${MAMMOTH_ROOT}/default") ||
  MAMMOTH_VERSION=system
fi

echo ${MAMMOTH_VERSION}

# Link Apache apxs lib
rm -f "${MAMMOTH_ROOT}"/lib/libphp*.so
LIBPHP_SO_FILE="libphp$(php-config --version | cut -c1).so"
APXS=""
if [ "${MAMMOTH_VERSION}" == "system" ]; then
    DEFAULT_APXS="$(which apxs 2>/dev/null)"
    if [ -n "${DEFAULT_APXS}" -a -f "$(${DEFAULT_APXS} -q LIBEXECDIR)/${LIBPHP_SO_FILE}" ]; then
	APXS="${DEFAULT_APXS}"
    fi
fi
php-config --configure-options 2>/dev/null | grep -q apxs  && \
    APXS="$(php-config --configure-options| sed 's/.*=\(.*apxs[^ ]*\) .*/\1/')"

[[ -d "${MAMMOTH_ROOT}/lib" ]] || mkdir "${MAMMOTH_ROOT}/lib"
if [ -n "${APXS}" ]; then
    [[ "${MAMMOTH_VERSION}" == "system" ]] && \
        ln -fs "$(${APXS} -q LIBEXECDIR)/${LIBPHP_SO_FILE}" "${MAMMOTH_ROOT}/lib/${LIBPHP_SO_FILE}" || \
        ln -fs "${MAMMOTH_ROOT}/versions/${MAMMOTH_VERSION}/libexec/${LIBPHP_SO_FILE}" "${MAMMOTH_ROOT}/lib/${LIBPHP_SO_FILE}";
fi
