#!/usr/bin/env bash
# Summary: List existing mammoth shims
# Usage: mammoth shims [--short]

set -e
[ -n "$MAMMOTH_DEBUG" ] && set -x

# Provide mammoth completions
if [ "$1" = "--complete" ]; then
  echo --short
  exit
fi

for command in "${MAMMOTH_ROOT}/shims/"*; do
  if [ "$1" = "--short" ]; then
    echo "${command##*/}"
  else
    echo "$command"
  fi
done | sort
